apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-rrd-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadOnlyMany
  nfs:
    server: honeycomb
    path: /mnt/ssd_nas/rrd
  mountOptions:
    - nfsvers=4.2
    - ro

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-rrd-pvc
  namespace: default
spec:
  accessModes:
    - ReadOnlyMany
  storageClassName: ""
  resources:
    requests:
      storage: 10Gi
  volumeName: nfs-rrd-pv

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-www-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: honeycomb
    path: /mnt/ssd_nas/www
  mountOptions:
    - nfsvers=4.2

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-www-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 10Gi
  volumeName: nfs-www-pv

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: graph-sensor-script
  namespace: default
data:
  graph_sensor_data.sh: |
    #!/bin/bash

    # Graph sensor data from RRD database
    # Generates graphs for 24 hours, 1 week, 1 month, and 1 year

    RRD_FILE="/data/rrd/sensors.rrd"
    OUTPUT_DIR="/data/www/weather_station"

    # Create output directory if it doesn't exist
    mkdir -p "$OUTPUT_DIR"

    # Colors for graphs
    COLOR_TEMP="#FF0000"      # Red for temperature
    COLOR_PRESSURE="#0000FF"  # Blue for pressure
    COLOR_HUMIDITY="#00AA00"  # Green for humidity
    COLOR_VOLTAGE="#FF8800"   # Orange for voltage

    # Function to create graphs
    create_graphs() {
        local period=$1
        local title=$2
        local start=$3

        # Temperature graph
        rrdtool graph "$OUTPUT_DIR/temperature_${period}.png" \
            --start "$start" \
            --title "Temperature - $title" \
            --vertical-label "Temperature (°F)" \
            --width 800 \
            --height 300 \
            DEF:temp="$RRD_FILE":temperature:AVERAGE \
            DEF:temp_min="$RRD_FILE":temperature:MIN \
            DEF:temp_max="$RRD_FILE":temperature:MAX \
            CDEF:temp_filtered=temp,-40,LT,UNKN,temp,60,GT,UNKN,temp,IF,IF \
            CDEF:temp_min_filtered=temp_min,-40,LT,UNKN,temp_min,60,GT,UNKN,temp_min,IF,IF \
            CDEF:temp_max_filtered=temp_max,-40,LT,UNKN,temp_max,60,GT,UNKN,temp_max,IF,IF \
            CDEF:temp_f=temp_filtered,9,*,5,/,32,+ \
            CDEF:temp_min_f=temp_min_filtered,9,*,5,/,32,+ \
            CDEF:temp_max_f=temp_max_filtered,9,*,5,/,32,+ \
            AREA:temp_max_f#FFCCCC:"Max" \
            AREA:temp_min_f#FFFFFF:"Min" \
            LINE2:temp_f$COLOR_TEMP:"Temperature" \
            GPRINT:temp_f:LAST:"Current\:%8.2lf °F" \
            GPRINT:temp_f:AVERAGE:"Average\:%8.2lf °F" \
            GPRINT:temp_min_f:MIN:"Min\:%8.2lf °F" \
            GPRINT:temp_max_f:MAX:"Max\:%8.2lf °F\n"

        # Pressure graph (converted to inches of mercury)
        rrdtool graph "$OUTPUT_DIR/pressure_${period}.png" \
            --start "$start" \
            --title "Atmospheric Pressure - $title" \
            --vertical-label "Pressure (inHg)" \
            --width 800 \
            --height 300 \
            --lower-limit 28.0 \
            --upper-limit 31.0 \
            --rigid \
            DEF:pressure="$RRD_FILE":pressure:AVERAGE \
            DEF:pressure_min="$RRD_FILE":pressure:MIN \
            DEF:pressure_max="$RRD_FILE":pressure:MAX \
            CDEF:pressure_inhg=pressure,33.8639,/ \
            CDEF:pressure_min_inhg=pressure_min,33.8639,/ \
            CDEF:pressure_max_inhg=pressure_max,33.8639,/ \
            AREA:pressure_max_inhg#CCCCFF:"Max" \
            AREA:pressure_min_inhg#FFFFFF:"Min" \
            LINE2:pressure_inhg$COLOR_PRESSURE:"Pressure" \
            GPRINT:pressure_inhg:LAST:"Current\:%8.2lf inHg" \
            GPRINT:pressure_inhg:AVERAGE:"Average\:%8.2lf inHg" \
            GPRINT:pressure_min_inhg:MIN:"Min\:%8.2lf inHg" \
            GPRINT:pressure_max_inhg:MAX:"Max\:%8.2lf inHg\n"

        # Humidity graph
        rrdtool graph "$OUTPUT_DIR/humidity_${period}.png" \
            --start "$start" \
            --title "Humidity - $title" \
            --vertical-label "Humidity (%)" \
            --width 800 \
            --height 300 \
            --lower-limit 0 \
            --upper-limit 100 \
            --rigid \
            DEF:humidity="$RRD_FILE":humidity:AVERAGE \
            DEF:humidity_min="$RRD_FILE":humidity:MIN \
            DEF:humidity_max="$RRD_FILE":humidity:MAX \
            AREA:humidity_max#CCFFCC:"Max" \
            AREA:humidity_min#FFFFFF:"Min" \
            LINE2:humidity$COLOR_HUMIDITY:"Humidity" \
            GPRINT:humidity:LAST:"Current\:%8.2lf %%" \
            GPRINT:humidity:AVERAGE:"Average\:%8.2lf %%" \
            GPRINT:humidity_min:MIN:"Min\:%8.2lf %%" \
            GPRINT:humidity_max:MAX:"Max\:%8.2lf %%\n"

        # Voltage graph (battery level)
        rrdtool graph "$OUTPUT_DIR/voltage_${period}.png" \
            --start "$start" \
            --title "Battery Voltage - $title" \
            --vertical-label "Voltage (V)" \
            --width 800 \
            --height 300 \
            --lower-limit 0 \
            --upper-limit 5 \
            DEF:voltage="$RRD_FILE":voltage:AVERAGE \
            DEF:voltage_min="$RRD_FILE":voltage:MIN \
            DEF:voltage_max="$RRD_FILE":voltage:MAX \
            AREA:voltage_max#FFEECC:"Max" \
            AREA:voltage_min#FFFFFF:"Min" \
            LINE2:voltage$COLOR_VOLTAGE:"Voltage" \
            GPRINT:voltage:LAST:"Current\:%8.2lf V" \
            GPRINT:voltage:AVERAGE:"Average\:%8.2lf V" \
            GPRINT:voltage_min:MIN:"Min\:%8.2lf V" \
            GPRINT:voltage_max:MAX:"Max\:%8.2lf V\n"

        echo "Generated graphs for $title in $OUTPUT_DIR/"
    }

    # Generate graphs for different time periods
    echo "Generating sensor graphs..."
    echo ""

    create_graphs "24h" "Last 24 Hours" "end-24h"
    create_graphs "1week" "Last Week" "end-1w"
    create_graphs "1month" "Last Month" "end-1month"
    create_graphs "1year" "Last Year" "end-1y"

    echo ""

    # Generate current_data.json for index.html
    echo "Generating current_data.json..."

    # Get the latest data from RRD
    # rrdtool lastupdate returns: timestamp: temp pressure humidity voltage
    LAST_UPDATE=$(rrdtool lastupdate "$RRD_FILE" | tail -n 1)

    if [ -n "$LAST_UPDATE" ]; then
        # Parse the last update (format: "timestamp: temp humidity pressure voltage")
        TIMESTAMP=$(echo "$LAST_UPDATE" | awk '{print $1}' | tr -d ':')
        TEMP_C=$(echo "$LAST_UPDATE" | awk '{print $2}')
        HUMIDITY=$(echo "$LAST_UPDATE" | awk '{print $3}')
        PRESSURE=$(echo "$LAST_UPDATE" | awk '{print $4}')
        VOLTAGE=$(echo "$LAST_UPDATE" | awk '{print $5}')

        # Convert temperature from Celsius to Fahrenheit
        TEMP_F=$(echo "$TEMP_C * 9 / 5 + 32" | bc -l)

        # Convert Unix timestamp to ISO 8601 format
        ISO_TIMESTAMP=$(date -d "@$TIMESTAMP" -Iseconds 2>/dev/null || date -r "$TIMESTAMP" -Iseconds 2>/dev/null)

        # Write JSON file atomically
        cat > "$OUTPUT_DIR/current_data.json.tmp" <<EOF
    {
      "temperature": $(printf "%.2f" "$TEMP_F"),
      "humidity": $(printf "%.1f" "$HUMIDITY"),
      "sea_level_pressure": $(printf "%.2f" "$PRESSURE"),
      "battery": $(printf "%.2f" "$VOLTAGE"),
      "timestamp": "$ISO_TIMESTAMP"
    }
    EOF

        # Atomic rename
        mv "$OUTPUT_DIR/current_data.json.tmp" "$OUTPUT_DIR/current_data.json"
        echo "Generated current_data.json with latest sensor readings"
    else
        echo "Warning: No data found in RRD database"
    fi

    echo ""
    echo "All graphs generated successfully!"
    echo "Output directory: $OUTPUT_DIR/"

---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: graph-sensor-data
  namespace: default
spec:
  # Run every 5 minutes
  schedule: "*/5 * * * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
          - name: graph-generator
            # Custom image with rrdtool and bash pre-installed
            image: docker-host:5000/rrdgraph:latest
            command:
            - /bin/bash
            - -c
            - |
              chmod +x /scripts/graph_sensor_data.sh
              /scripts/graph_sensor_data.sh
            volumeMounts:
            - name: script
              mountPath: /scripts
            - name: rrd-data
              mountPath: /data/rrd
              readOnly: true
            - name: www-output
              mountPath: /data/www
            resources:
              requests:
                memory: "64Mi"
                cpu: "100m"
              limits:
                memory: "256Mi"
                cpu: "500m"
          volumes:
          - name: script
            configMap:
              name: graph-sensor-script
              defaultMode: 0755
          - name: rrd-data
            persistentVolumeClaim:
              claimName: nfs-rrd-pvc
          - name: www-output
            persistentVolumeClaim:
              claimName: nfs-www-pvc
