---
# NFS-based storage for RRD data on NAS
# This keeps your data centralized and safe on your NAS
#
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mqtt-monitor-rrd-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany  # NFS supports multiple readers/writers
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  nfs:
    server: <NAS_IP_OR_HOSTNAME>  # e.g., 192.168.1.10 or nas.local
    path: <NFS_EXPORT_PATH>        # e.g., /volume1/k3s/mqtt-monitor or /mnt/data/rrd
    readOnly: false
  mountOptions:
    - nfsvers=4.1
    - hard
    - timeo=600
    - retrans=2
    - rsize=1048576
    - wsize=1048576

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mqtt-monitor-rrd-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs
  resources:
    requests:
      storage: 1Gi
